/**
 * @packageDocumentation
 * @module routes/auto
 * @since 1.0.0 (2025-12-30)
 * @author Z-kali
 * @description 基于 API 配置自动生成的路由 - 示例
 */

import { buildRoutesFromApis } from "../builder";
import { allApis } from "@/config/catalog";

/**
 * @constant autoGeneratedRoutes
 * @description 自动生成的路由器
 * 
 * 这个路由器会自动从 data/api/*.json 中的 API 配置生成所有路由
 * 包括:
 * - 自动认证检查
 * - 自动角色验证
 * - 自动绑定 CRUD 控制器
 * - 自动缓存配置
 */
export const autoGeneratedRoutes = buildRoutesFromApis(allApis, {
  autoAuth: true,        // 启用自动认证
  autoRoleCheck: true,   // 启用自动角色检查
});

export default autoGeneratedRoutes;
